[project]
name = "qosst-skr"
description = "Secret Key Rate (SKR) submodule of QOSST, with the different methods to compute the Secret Key Rate."
authors = [{ name = "Yoann Piétri", email = "Yoann.Pietri@lip6.fr" }]
license = "GPL-3.0-only"
readme = "README.md"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Security :: Cryptography",
]

requires-python = ">=3.10, <3.15"
dynamic = ["version"]

dependencies = ["qosst-core @ git+https://github.com/qosst/qosst-core@dev"]

[project.urls]
homepage = "https://github.com/qosst"
repository = "https://github.com/qosst/qosst-skr"
documentation = "https://qosst-skr.readthedocs.io/"


[tool.poetry]

version = "0.10.0.dev0"
packages = [{ include = "qosst_skr" }, { include = "qosst_skr/py.typed" }]

[tool.poetry.group.dev.dependencies]
myst-parser = "^4.0.0"
Sphinx = "^8.1.0"
sphinx-rtd-theme = "^3.0.0"
setuptools = "^82.0.1"
docstr-coverage = "^2.2.0"
pylint = "^4.0.5"
black = "^26.3.1"
mypy = "^1.3.0"
sphinx-prompt = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
